# Generated by Django 5.1.6 on 2025-03-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_placed', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
